language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t thembani/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thembani/docker-react npm run test


